### ISSUE TITLE
Migration plan: draft a migration process

### ISSUE THREAD

**Issue by metasj** [prior-art-archive/overview#15]
We talked about setting up fully separate dev + prod stacks for migration purposes.  
And need a timeline + more detailed migration plan:

**Devops**
- Separate dev + prod.  (does this extend down to IPFS?)
- Define test + update processes.

**Upgrade dev**
- Test w/ existing + new data, fix blockers.  Test UL + IPFS components
- Test: Compare search results w/ prod, fix experience blockers

**Migrate**
- Set up CI / code elevation practices
- Push changes (retain legacy version for a time for comparison + debugging )

**Comment by slifty** [comment]
This is now captured in a wiki page that we can add to / flesh out: https://github.com/prior-art-archive/overview/wiki/2019-Migration

The specific issues linked to the v2 migration are in the [v2 deployment milestone](https://github.com/prior-art-archive/priorartarchive.org/milestone/1) <-- this list will change as we make progress / identify more issues.

**Comment by slifty** [comment]
I got a 👍 in slack on this, so closing the issue!
