### ISSUE TITLE
Getting local dev environments set up

### ISSUE THREAD

**Issue by slifty** [prior-art-archive/overview#24]
Dan and Justin need to get to the point they can contribute to search / migration, and update documentation if they face any issues.

* [x] Dan dev envionment
* [x] Justin dev environment

This shouldn't take long, but worth having the issue in the spirit of "only work on things with issues"

**Comment by reefdog** [comment]
We're all setup for dev'ing and deploying [priorartarchive.org](https://github.com/prior-art-archive/priorartarchive.org). :tada: We aren't including setup for any of the Lambda functions yet; we'll tackle them as needed.
