### ISSUE TITLE
Migrate issues from Trello to Github

### ISSUE THREAD

**Issue by metasj** [prior-art-archive/overview#3]
Issues and features from the prior [board](https://trello.com/b/VY3SYRDj/priorart-development
) need migration.  ([Join the board](https://trello.com/invite/b/VY3SYRDj/71f54e0c17cdf25851ce44053fc195d1/priorart-development) to see it)

**Comment by metasj** [comment]
Mostly done.   A dozen enhancements + other FRs remain.

**Comment by slifty** [comment]
@metasj We should move the final ones over so we can close out this issue!

I have access to the board so I would be glad to take a stab there; is there an indication of which cards have not been copied over to github?

**Comment by metasj** [comment]
I've made a [list](https://trello.com/b/VY3SYRDj/priorart-development) for "not migrated" ideas and feature requests.  Some have been combined into an updated request here; others will be future issues.  There are also past issues that deserve revisiting after the migration.

**Comment by slifty** [comment]
I think for the intended scope of this issue then we can close this (the goal was to get the github board in a state that reflected the work we need to do in the short / mid term and I think we're there)
