### ISSUE TITLE
Move lambda code into github

### ISSUE THREAD

**Issue by slifty** [prior-art-archive/overview#31]
We have some code that is core to the project but doesn't actually live in any code repository (lambda functions are the big ones, but there are also little things like the code behind the querystring parser jar from prior-art-archive/priorartarchive.org#32. If the latter category ends up being significant we may want to create a separate issue for that kind of code.)

We want to move to a lambda framework (maybe something like [serverless](https://serverless.com/) that allows us to work with the code through github and just treat lambda as a deployment architecture.

NOTE: it sounds like the string parser may be the only thing being handled on lambda; if that is the case we probably want to consider closing this issue and instead just planning to convert that to a client side parser.

**Comment by reefdog** [comment]
The Lambda functions [file-parser](https://github.com/prior-art-archive/file-parser), [sftp-authentication](https://github.com/prior-art-archive/sftp-authentication), and [sftp-copy](https://github.com/prior-art-archive/sftp-copy) are here already. Those three plus `priorart-search-parser` are represented in the [architecture diagram here](https://camo.githubusercontent.com/4606f3fb4e429ac6a5fa3e083bf150866252447f/68747470733a2f2f692e696d6775722e636f6d2f316d47656f465a2e706e67), I don't know if there are additional functions not represented; @joeltg?

**Comment by joeltg** [comment]
`file-parser` isn't a lambda function, it's a multi-docker container deployment on Elastic Beanstalk. `priorart-search-parser` is mislabeled in the architecture diagram - it is a lambda function, but it's named `queryParser`.

**Comment by joeltg** [comment]
There are no additional lambda functions.

**Comment by reefdog** [comment]
Ah sorry, I thought file-parser was triggered by a Lambda function.

**Comment by reefdog** [comment]
Everything is in GH that needs to be, and we'll be moving away from the [Lambda-hosted version of query-parser](https://github.com/prior-art-archive/query-parser/) to the [Dockerized version](https://github.com/prior-art-archive/query-parser-docker/) (until [rewriting](https://github.com/prior-art-archive/priorartarchive.org/issues/55)).
