### ISSUE TITLE
Bug: Items without titles can't be viewed and need a title-place-holder

### ISSUE THREAD

**Issue by metasj** [prior-art-archive/overview#7]
As a browser, if I run a search that returns a document without a title, I should be able to click on something to see the article. [No title] or equivalent is fine], though we should also catch that and give uploaders feedback.

**Comment by joeltg** [comment]
I think this has been solved for a while - even on v1 production
 
<img width="640" alt="Screen Shot 2019-04-24 at 9 47 14 AM" src="https://user-images.githubusercontent.com/8454646/56664493-34d41880-6676-11e9-8797-01fbc900ec08.png">
<img width="495" alt="Screen Shot 2019-04-24 at 9 48 37 AM" src="https://user-images.githubusercontent.com/8454646/56664499-38679f80-6676-11e9-8498-80d29d31a83e.png">

**Comment by reefdog** [comment]
This was going to be my "get acquainted" task of the day. Can we create a new bug for me to handle instead? 😛 Kidding, glad this is ✅!

**Comment by metasj** [comment]
Better first bug: create better default title when none is found; :)
